"""Initial migration.

Revision ID: 549b09035ca6
Revises: 
Create Date: 2024-10-12 09:19:39.053340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549b09035ca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices', sa.String(length=255), nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_a')
        batch_op.drop_column('option_c')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'module', ['module_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('module_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_c', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('option_a', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('option_d', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('option_b', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.drop_column('choices')

    # ### end Alembic commands ###
